### ISSUE TITLE
Use of autoscroll

### ISSUE THREAD

**Issue by invaders-xx** [Accudio/alpine-splide#2]
Hi,
Many thanks for this package.

I wonder how to integrate [splide-extension-auto-scroll](https://github.com/Splidejs/splide-extension-auto-scroll) extension.
Any thoughts ?

Many thanks in advance.

**Comment by Accudio** [comment]
Hi @invaders-xx 

There isn't a way of importing any extensions at the moment and I don't currently intend to do so — this is a fairly simple base package and I think adding something like that would be a bigger addition than necessary.

That said, you could make a fork of the package and import splide-extension-auto-scroll within this file: https://serieseight.slack.com/archives/C044B5E9C66/p1680779554304339?thread_ts=1680779254.537619&cid=C044B5E9C66

Or if you have a build system set up for Alpine, you could copy that component file into your own project and import whatever extensions you want.
