### ISSUE TITLE
SPA usecase

### ISSUE THREAD

**Issue by yamakrane** [Accudio/alpine-splide#3]
How to init Slide on demand, i use turbolinks for SPA feel. Trying to get it work like that maybe ?

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) {
      new Splide( '#image-slider' ).mount();
  });
</script>

**Comment by Accudio** [comment]
Alpine.js uses a `MutationObserver` to initialise components when they enter the DOM so client side routing should work just fine with no additions necessary.

Alpine Splide doesn't do anything fancy here, it works like a normal Alpine component. If you aren't sure how Alpine component loading works you can refer to the [Alpine docs](https://alpinejs.dev/start-here), [GitHub](https://github.com/alpinejs/alpine) or ask a question in [the Discord](https://alpinejs.codewithhugo.com/chat/).

**Comment by yamakrane** [comment]
i have to reload the page so that it recognizes Splide. Then I just need a hint if you don't mind.

**Comment by yamakrane** [comment]
npm run dev, was causing that. thanks
